/**
 * Common Norwegian shopping items with pre-assigned categories
 * Shared between client cache and server API to ensure consistency
 */

import type { ShoppingCategory } from './constants'

/**
 * Pre-defined category mappings for common Norwegian grocery items
 * Keys are lowercase, normalized item names
 * Includes both singular and plural forms where applicable
 */
export const COMMON_ITEMS: Record<string, ShoppingCategory> = {
  // ============= DAIRY (Meieri) =============
  'melk': 'dairy',
  'mjølk': 'dairy',
  'lettmelk': 'dairy',
  'helmelk': 'dairy',
  'skummet melk': 'dairy',
  'egg': 'dairy',
  'smør': 'dairy',
  'ost': 'dairy',
  'hvitost': 'dairy',
  'brunost': 'dairy',
  'kremost': 'dairy',
  'yoghurt': 'dairy',
  'rømme': 'dairy',
  'fløte': 'dairy',
  'kremfløte': 'dairy',
  'matfløte': 'dairy',

  // ============= PRODUCE (Frukt og grønt) =============
  'eple': 'produce',
  'epler': 'produce',
  'banan': 'produce',
  'bananer': 'produce',
  'appelsin': 'produce',
  'appelsiner': 'produce',
  'sitron': 'produce',
  'sitroner': 'produce',
  'tomat': 'produce',
  'tomater': 'produce',
  'agurk': 'produce',
  'salat': 'produce',
  'isbergsalat': 'produce',
  'løk': 'produce',
  'rødløk': 'produce',
  'hvitløk': 'produce',
  'gulrot': 'produce',
  'gulrøtter': 'produce',
  'potet': 'produce',
  'poteter': 'produce',
  'brokkoli': 'produce',
  'blomkål': 'produce',
  'paprika': 'produce',
  'avokado': 'produce',
  'sopp': 'produce',
  'sjampinjong': 'produce',
  'spinat': 'produce',
  'grønnkål': 'produce',
  'persille': 'produce',
  'basilikum': 'produce',
  'dill': 'produce',
  'ingefær': 'produce',
  'druer': 'produce',
  'jordbær': 'produce',
  'blåbær': 'produce',
  'bringebær': 'produce',
  'mango': 'produce',
  'ananas': 'produce',
  'melon': 'produce',
  'pære': 'produce',
  'pærer': 'produce',
  'kiwi': 'produce',

  // ============= MEAT (Kjøtt og fisk) =============
  'kjøttdeig': 'meat',
  'karbonadedeig': 'meat',
  'kylling': 'meat',
  'kyllingfilet': 'meat',
  'kyllinglår': 'meat',
  'biff': 'meat',
  'entrecote': 'meat',
  'svinekjøtt': 'meat',
  'koteletter': 'meat',
  'bacon': 'meat',
  'pølser': 'meat',
  'wienerpølser': 'meat',
  'grillpølser': 'meat',
  'laks': 'meat',
  'laksefilet': 'meat',
  'røkelaks': 'meat',
  'torsk': 'meat',
  'torskefilet': 'meat',
  'sei': 'meat',
  'fisk': 'meat',
  'reker': 'meat',
  'sjømat': 'meat',
  'skinke': 'meat',
  'spekeskinke': 'meat',
  'salami': 'meat',
  'leverpostei': 'meat',

  // ============= PANTRY (Tørrvarer) =============
  'brød': 'pantry',
  'grovbrød': 'pantry',
  'loff': 'pantry',
  'rundstykker': 'pantry',
  'boller': 'pantry',
  'pasta': 'pantry',
  'spaghetti': 'pantry',
  'penne': 'pantry',
  'makaroni': 'pantry',
  'ris': 'pantry',
  'jasminris': 'pantry',
  'basmatiris': 'pantry',
  'mel': 'pantry',
  'hvetemel': 'pantry',
  'sukker': 'pantry',
  'melis': 'pantry',
  'salt': 'pantry',
  'pepper': 'pantry',
  'krydder': 'pantry',
  'olje': 'pantry',
  'olivenolje': 'pantry',
  'rapsolje': 'pantry',
  'eddik': 'pantry',
  'soya': 'pantry',
  'soyasaus': 'pantry',
  'ketchup': 'pantry',
  'sennep': 'pantry',
  'majones': 'pantry',
  'hermetikk': 'pantry',
  'tomater på boks': 'pantry',
  'bønner': 'pantry',
  'kikerter': 'pantry',
  'knekkebrød': 'pantry',
  'havregryn': 'pantry',
  'cornflakes': 'pantry',
  'müsli': 'pantry',
  'taco': 'pantry',
  'tacoskjell': 'pantry',
  'lefser': 'pantry',
  'tortilla': 'pantry',
  'nudler': 'pantry',
  'nøtter': 'pantry',
  'mandler': 'pantry',
  'rosiner': 'pantry',
  'sjokolade': 'pantry',
  'chips': 'pantry',
  'kjeks': 'pantry',
  'syltetøy': 'pantry',
  'honning': 'pantry',
  'peanøttsmør': 'pantry',
  'nutella': 'pantry',

  // ============= FROZEN (Frysevarer) =============
  'pizza': 'frozen',
  'frossenpizza': 'frozen',
  'grandiosa': 'frozen',
  'fiskepinner': 'frozen',
  'fiskekaker': 'frozen',
  'is': 'frozen',
  'iskrem': 'frozen',
  'frosne grønnsaker': 'frozen',
  'frosne bær': 'frozen',
  'pommes frites': 'frozen',
  'nuggets': 'frozen',
  'pølsebrød': 'frozen',

  // ============= BEVERAGES (Drikkevarer) =============
  'juice': 'beverages',
  'appelsinjuice': 'beverages',
  'eplejuice': 'beverages',
  'brus': 'beverages',
  'cola': 'beverages',
  'pepsi': 'beverages',
  'fanta': 'beverages',
  'solo': 'beverages',
  'vann': 'beverages',
  'mineralvann': 'beverages',
  'farris': 'beverages',
  'kaffe': 'beverages',
  'te': 'beverages',
  'øl': 'beverages',
  'vin': 'beverages',
  'saft': 'beverages',

  // ============= HOUSEHOLD (Husholdning) =============
  'toalettpapir': 'household',
  'dopapir': 'household',
  'tørkepapir': 'household',
  'kjøkkenruller': 'household',
  'såpe': 'household',
  'håndsåpe': 'household',
  'oppvaskmiddel': 'household',
  'vaskemiddel': 'household',
  'tøymykner': 'household',
  'tannkrem': 'household',
  'tannbørste': 'household',
  'sjampo': 'household',
  'balsam': 'household',
  'dusjsåpe': 'household',
  'deodorant': 'household',
  'bleier': 'household',
  'våtservietter': 'household',
  'servietter': 'household',
  'plastfolie': 'household',
  'bakepapir': 'household',
  'aluminiumsfolie': 'household',
  'avfallsposer': 'household',
  'søppelposer': 'household',
  'rengjøringsmiddel': 'household',
  'klorin': 'household',

  // ============= HOME (Hjem) =============
  'lyspære': 'home',
  'batterier': 'home',
  'stearinlys': 'home',
  'blomster': 'home',
  'plante': 'home',
  'verktøy': 'home',
  'skruer': 'home',
  'tape': 'home',
  'lim': 'home',

  // ============= ELECTRONICS (Elektronikk) =============
  'lader': 'electronics',
  'ladekabel': 'electronics',
  'kabel': 'electronics',
  'usb': 'electronics',
  'usb-kabel': 'electronics',
  'adapter': 'electronics',
  'hodetelefoner': 'electronics',
  'ørepropper': 'electronics',
}

/**
 * Normalize item name for cache lookup
 * Simple normalization - just lowercase and trim
 * No suffix removal to avoid false matches
 */
export function normalizeItemName(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, ' ')
}

/**
 * Get category from common items dictionary
 * Returns undefined if not found
 */
export function getCommonItemCategory(itemName: string): ShoppingCategory | undefined {
  const normalized = normalizeItemName(itemName)
  return COMMON_ITEMS[normalized]
}
