/**
 * PR-Specific Test Scenarios
 *
 * Executes test scenarios generated by the AI PR test generator.
 * These tests are dynamically created based on what changed in the PR.
 *
 * The test generator creates tests/e2e/generated/pr-scenarios.json
 * which this file reads and executes.
 *
 * Run with: npx playwright test tests/e2e/pr-scenarios.spec.ts
 */

import { test, expect, Page, BrowserContext } from '@playwright/test'
import { existsSync, readFileSync } from 'fs'
import { join } from 'path'
import { setupTestFixture } from './fixtures/mock-auth'

// ============================================
// Types
// ============================================

interface TestScenario {
  id: string
  name: string
  description: string
  priority: 'critical' | 'high' | 'medium' | 'low'
  page: string
  viewport?: 'mobile' | 'desktop'
  needsAuth: boolean
  needsDemo: boolean
  steps: TestStep[]
  assertions: TestAssertion[]
  relatedFiles: string[]
  prContext: string
}

interface TestStep {
  action: 'goto' | 'click' | 'fill' | 'wait' | 'scroll' | 'hover'
  target?: string
  value?: string
  waitFor?: string
  timeout?: number
}

interface TestAssertion {
  type: 'visible' | 'hidden' | 'text' | 'url' | 'count' | 'attribute'
  target: string
  value?: string
  count?: number
  attribute?: { name: string; value: string }
}

interface GeneratedTests {
  prTitle: string
  prDescription: string
  generatedAt: string
  scenarios: TestScenario[]
}

// ============================================
// Helpers
// ============================================

function loadScenarios(): TestScenario[] {
  const scenariosPath = join(__dirname, 'generated', 'pr-scenarios.json')

  if (!existsSync(scenariosPath)) {
    console.log('No PR-specific scenarios found. Run: npx tsx scripts/ai-pr-test-generator.ts')
    return []
  }

  try {
    const content = readFileSync(scenariosPath, 'utf-8')
    const data: GeneratedTests = JSON.parse(content)
    console.log(`📋 Loaded ${data.scenarios.length} PR-specific scenarios`)
    console.log(`   PR: ${data.prTitle}`)
    console.log(`   Generated: ${data.generatedAt}`)
    return data.scenarios
  } catch (error) {
    console.error('Failed to load scenarios:', error)
    return []
  }
}

async function executeStep(page: Page, step: TestStep): Promise<void> {
  const timeout = step.timeout || 10000

  switch (step.action) {
    case 'goto':
      if (step.target) {
        await page.goto(step.target, { waitUntil: 'networkidle', timeout })
      }
      break

    case 'click':
      if (step.target) {
        await page.locator(step.target).first().click({ timeout })
      }
      break

    case 'fill':
      if (step.target && step.value !== undefined) {
        await page.locator(step.target).first().fill(step.value, { timeout })
      }
      break

    case 'wait':
      if (step.waitFor) {
        await page.waitForSelector(step.waitFor, { timeout })
      } else if (step.timeout) {
        await page.waitForTimeout(step.timeout)
      }
      break

    case 'scroll':
      if (step.target) {
        await page.locator(step.target).first().scrollIntoViewIfNeeded()
      }
      break

    case 'hover':
      if (step.target) {
        await page.locator(step.target).first().hover({ timeout })
      }
      break
  }
}

async function checkAssertion(page: Page, assertion: TestAssertion): Promise<void> {
  const timeout = 10000

  switch (assertion.type) {
    case 'visible':
      await expect(page.locator(assertion.target).first()).toBeVisible({ timeout })
      break

    case 'hidden':
      await expect(page.locator(assertion.target).first()).toBeHidden({ timeout })
      break

    case 'text':
      if (assertion.value) {
        await expect(page.locator(assertion.target).first()).toContainText(assertion.value, { timeout })
      }
      break

    case 'url':
      await expect(page).toHaveURL(new RegExp(assertion.target), { timeout })
      break

    case 'count':
      if (assertion.count !== undefined) {
        await expect(page.locator(assertion.target)).toHaveCount(assertion.count, { timeout })
      }
      break

    case 'attribute':
      if (assertion.attribute) {
        await expect(page.locator(assertion.target).first()).toHaveAttribute(
          assertion.attribute.name,
          assertion.attribute.value,
          { timeout }
        )
      }
      break
  }
}

async function setupScenario(
  page: Page,
  context: BrowserContext,
  scenario: TestScenario
): Promise<void> {
  // Set viewport if specified
  if (scenario.viewport === 'mobile') {
    await page.setViewportSize({ width: 375, height: 667 })
  }

  // Setup mock auth if needed
  if (scenario.needsAuth || scenario.needsDemo) {
    await setupTestFixture(context, page, {
      childCount: 2,
      memberCount: 2,
      withPickups: true,
      withMeals: true,
      withEvents: true,
      withTasks: true,
    })
  }
}

// ============================================
// Tests
// ============================================

const scenarios = loadScenarios()

if (scenarios.length === 0) {
  // Create a placeholder test when no scenarios exist
  test('No PR-specific scenarios to run', async () => {
    console.log('No scenarios were generated for this PR.')
    console.log('This is normal if:')
    console.log('  - The PR only contains documentation changes')
    console.log('  - The AI test generator was not run')
    console.log('  - The PR has no testable UI changes')
    expect(true).toBe(true)
  })
} else {
  // Group tests by priority
  const criticalScenarios = scenarios.filter(s => s.priority === 'critical')
  const highScenarios = scenarios.filter(s => s.priority === 'high')
  const otherScenarios = scenarios.filter(s => s.priority === 'medium' || s.priority === 'low')

  // Critical tests run first
  if (criticalScenarios.length > 0) {
    test.describe('🔴 Critical PR Tests', () => {
      for (const scenario of criticalScenarios) {
        test(scenario.name, async ({ page, context }) => {
          await runScenario(page, context, scenario)
        })
      }
    })
  }

  // High priority tests
  if (highScenarios.length > 0) {
    test.describe('🟠 High Priority PR Tests', () => {
      for (const scenario of highScenarios) {
        test(scenario.name, async ({ page, context }) => {
          await runScenario(page, context, scenario)
        })
      }
    })
  }

  // Other tests
  if (otherScenarios.length > 0) {
    test.describe('🟢 Additional PR Tests', () => {
      for (const scenario of otherScenarios) {
        test(scenario.name, async ({ page, context }) => {
          await runScenario(page, context, scenario)
        })
      }
    })
  }
}

async function runScenario(
  page: Page,
  context: BrowserContext,
  scenario: TestScenario
): Promise<void> {
  console.log(`\n📋 Scenario: ${scenario.name}`)
  console.log(`   Description: ${scenario.description}`)
  console.log(`   Page: ${scenario.page}`)
  console.log(`   PR Context: ${scenario.prContext}`)

  // Setup the scenario
  await setupScenario(page, context, scenario)

  // Navigate to the target page
  const baseUrl = process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:3000'
  const targetUrl = scenario.page.startsWith('http') ? scenario.page : `${baseUrl}${scenario.page}`
  await page.goto(targetUrl, { waitUntil: 'networkidle' })

  // Execute steps
  for (let i = 0; i < scenario.steps.length; i++) {
    const step = scenario.steps[i]
    console.log(`   Step ${i + 1}: ${step.action}${step.target ? ` → ${step.target}` : ''}`)

    try {
      await executeStep(page, step)
    } catch (error) {
      console.error(`   ❌ Step ${i + 1} failed:`, error)
      throw error
    }
  }

  // Check assertions
  for (let i = 0; i < scenario.assertions.length; i++) {
    const assertion = scenario.assertions[i]
    console.log(`   Assertion ${i + 1}: ${assertion.type} → ${assertion.target}`)

    try {
      await checkAssertion(page, assertion)
      console.log(`   ✅ Assertion ${i + 1} passed`)
    } catch (error) {
      console.error(`   ❌ Assertion ${i + 1} failed:`, error)
      throw error
    }
  }

  console.log(`   ✅ Scenario passed: ${scenario.name}`)
}
